blank_issues_enabled: false
contact_links:
  - name: ❓Questions about using Mavis SDK
    url: https://github.com/Mavis2103/mavis-sdk/discussions/categories/q-a
    about: Please ask and answer questions in GitHub Discussions under Q&A category
    
  - name: 📚 Documentation
    url: https://Mavis2103.github.io/mavis-sdk/
    about: Check the documentation first - your question might already be answered

  - name: 🧠 Ideas & Suggestions
    url: https://github.com/Mavis2103/mavis-sdk/discussions/categories/ideas
    about: Share ideas and suggestions in GitHub Discussions under Ideas category

  - name: 🗨️ Community Chat
    url: https://discord.gg/KCeEjr94DG
    about: For quick questions and community chat, join our Discord server
