remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
'@mavis-sdk/experimental on GitHub':
  - 'https://github.com/anastasia-labs/lucid-evolution'